name: flutter_task_planner_app

description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

firebase_core : any

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  percent_indicator: ^4.0.0
  cloud_firestore: ^3.1.6
  syncfusion_flutter_calendar: ^19.4.43
  table_calendar: ^3.0.3
  calendar_timeline: ^1.0.4
  flutter_calendar_carousel : 
  date_picker_timeline: ^1.2.3
  synchronized: ^3.0.0
  clock: ^1.1.0
  fake_async: ^1.2.0
  test: ^1.19.5
  flutter_analog_clock: ^0.1.1
  analog_clock: ^0.1.0
  flutter_countdown_timer: ^4.1.0
  timeline_tile: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800

  